### ISSUE TITLE
Cannot install chrome extension

### ISSUE THREAD

**Issue by realyukii** [subhra74/xdm#1123]
**Describe the bug**
Try to install browser monitoring extension on chrome

**To Reproduce**
1. Go to XDM app
2. Click on tools > browser monitoring > chrome
3. Go to site https://subhra74.github.io/xdm/redirect.html?target=chrome
4. After redirected, See error 404 on https://chrome.google.com/webstore/detail/xtreme-download-manager/dkckaoghoiffdbomfbbodbbgmhjblecj

**Expected behavior**
The chrome webstore must not be 404

**Screenshots**
![image](https://github.com/subhra74/xdm/assets/126035476/2fe7bf79-d45b-4846-8c38-d13c609daad4)

**please complete the following information:**
 - OS: Windows
 - Browser chrome
 - XDM addon Version none
 - XDM Version 7.2.11

**Comment by realyukii** [comment]
work after upgrading to latest beta version

**Comment by imdupeng** [comment]
Version 7.2.11 has the same problem

**Comment by joselmm** [comment]
I UPDATED THE EXTENSION TO MANIFEST V3,'
but due to the cors issue, I also had to update
the xdman.jr that is in the root folder of XDM,
YOU NEED TO DOWNLOAD my version of [xdman.jar](https://github.com/joselmm/xdm-2023/raw/main/xdman.jar) and replace the one in the root folder (DON'T FORGET TO GO TO "File" --> "Exit" first).

YOU MUST ENABLE DEVELOPER MODE IN CHROME, IN EXTENSIONS,
![1](https://github.com/subhra74/xdm/assets/95531879/c58eadd1-fb95-495b-820f-7f2fcb3370e5)


[HERE IS THE EXTENSION](https://github.com/joselmm/xdm-2023/raw/main/xdm-extesion-manifest-v3.zip). YOU MUST UNZIP AND DRAG AND DROP THE "xdm-extesion-manifest-v3" FOLDER
![2](https://github.com/subhra74/xdm/assets/95531879/67435c03-822a-4625-9166-574a5ec2b2a2)
THEN IT MUST APPEAR LIKE THIS:
![3](https://github.com/subhra74/xdm/assets/95531879/9727e8b6-ae3e-43ff-bdb3-a976a36e783f)


THIS IS MY VERSION OF xdman.jar:
![4](https://github.com/subhra74/xdm/assets/95531879/01c45dc3-e82d-4b4c-976a-b547ffc03090)
