### ISSUE TITLE
Auto Download is Doesnt Work

### ISSUE THREAD

**Issue by G33DO** [subhra74/xdm#90]
Hello, I'm using xdm 7.2.10 and got auto download problem.

So it was happened when I want to download from a vod (I think we should say it here because its too risky).
So this vod do is just split videos and audios into small parts that xdm can capture to download them all when we're streaming.
But the thing is, I need to download them all automatically so I dont need to download them one by one,

I tried to activate the auto download setting, but its doesnt work.

And I dont know what xdm extension functions, because when I right click on that xdm extension on firefox to download all the xdm's captures, its all downloaded with html formats and the mp4 or mp4a from that streaming were doesnt appear, they only appear when I left click the extension to download them one by one and (the mp4 or mp4a) appear on the floating download too
so the only thing I can do is download them one by one (its around 1000 files btw)

Anyway thank you for sharing to us this incredible software, Im so happy this software can read all the streaming data, but it will be better if we get an easier to download them all.

*n.b. I cant share any screenshots because its too risky, and I hope you delete this issue after the problem was solved

**Comment by subhra74** [comment]
As off now XDM does not allow auto download of video streams. XDM can only detect the streams when being played in browser. What you can do is to play each video for about 2-3 sec, so that XDM can detect the streams. Then you can add the downloads to XDM queue and start the queue.



### image
![image](https://user-images.githubusercontent.com/8403090/78118564-78e3a780-7407-11ea-8a72-4dccb00d01fb.png)

**Comment by G33DO** [comment]
I'm sorry my mistake, the vod has been protected by drm
pls delete this issue
thank you for the answer btw.
