### ISSUE TITLE
Google chrome addon(extension) link is broken

### ISSUE THREAD

**Issue by omerap12** [subhra74/xdm#934]
### XDM is currently being re-written to be more user friendly and performant, please refer to (https://github.com/subhra74/xdm/discussions/768) for more information ###

**PLEASE DO NOT JUST SAY "It does not work, or something not working etc." Provide enough relevent details so that the issue can be analyzed and reproduced easily**

**Describe the bug**

**To Reproduce**
1. Go to github page (https://github.com/subhra74/xdm) or using the app.
2. Click on Google chrome addon
4. See error - "The requested URL was not found on this server. That’s all we know."

**Expected behavior**
I expected to be directed to the extension download page.

**Screenshots**
![image](https://user-images.githubusercontent.com/61663422/201340180-6d6bdce1-4b5f-46f8-b609-8ecaaed908e0.png)

**please complete the following information:**
 - OS: [e.g. Linux/Windows] Linux
 - Browser [e.g. chrome, Firefox] Chrome
 - XDM addon Version [e.g. 2.0]  NA
 - XDM Version [e.g. 7.2.0] 7.2.11

**Generated log using below method**
 - https://github.com/subhra74/xdm/wiki/Generate-log-for-troubleshooting

**Additional context**

**Comment by teknowene** [comment]
Yah I am getting similar issues on Windows... It Seems that the extensions are just missing....
Michael

**Comment by omerap12** [comment]
@teknowene 
Well, is there a way to find the extension? (I tried to search it but no luck so far)

**Comment by x00jahangir** [comment]
Found workaround.

- Clone this https://github.com/subhra74/xdm-browser-monitor
- Load `xdm-browser-monitor/chrome` folder as unpacked extension.

![XDM integration](https://i.imgur.com/wuPi65Z.gif)

**Comment by esyede** [comment]
In case someone needs the `.crx` version, here it is:
Just extract the zip archive then drag & drop it to the extension page

[dkckaoghoiffdbomfbbodbbgmhjblecj.zip](https://github.com/subhra74/xdm/files/10097302/dkckaoghoiffdbomfbbodbbgmhjblecj.zip)

**Comment by omerap12** [comment]
Works! 
@x00jahangir @esyede Thanks!

**Comment by joselmm** [comment]
I UPDATED THE EXTENSION TO MANIFEST V3,'
but due to the cors issue, I also had to update
the xdman.jr that is in the root folder of XDM,
YOU NEED TO DOWNLOAD my version of [xdman.jar](https://github.com/joselmm/xdm-2023/raw/main/xdman.jar) and replace the one in the root folder (DON'T FORGET TO GO TO "File" --> "Exit" first).

YOU MUST ENABLE DEVELOPER MODE IN CHROME, IN EXTENSIONS,
![1](https://github.com/subhra74/xdm/assets/95531879/c58eadd1-fb95-495b-820f-7f2fcb3370e5)


[HERE IS THE EXTENSION](https://github.com/joselmm/xdm-2023/raw/main/xdm-extesion-manifest-v3.zip). YOU MUST UNZIP AND DRAG AND DROP THE "xdm-extesion-manifest-v3" FOLDER
![2](https://github.com/subhra74/xdm/assets/95531879/67435c03-822a-4625-9166-574a5ec2b2a2)
THEN IT MUST APPEAR LIKE THIS:
![3](https://github.com/subhra74/xdm/assets/95531879/9727e8b6-ae3e-43ff-bdb3-a976a36e783f)


THIS IS MY VERSION OF xdman.jar:
![4](https://github.com/subhra74/xdm/assets/95531879/01c45dc3-e82d-4b4c-976a-b547ffc03090)
