### ISSUE TITLE
Chrome browser extension just disappeared

### ISSUE THREAD

**Issue by Charles2205** [subhra74/xdm#938]
### Discussed in https://github.com/subhra74/xdm/discussions/898

<div type='discussions-op-text'>

<sup>Originally posted by **sumeetsingh39** September 24, 2022</sup>
Chrome extension just disappeared recently from my system, and the URL to install the extension doesn't work.</div>

**Comment by lorens-osman-dev** [comment]
me to

**Comment by ThePhantom6314** [comment]
CRX Reupload: https://www.mediafire.com/file/d0io0x4oet9umct/dkckaoghoiffdbomfbbodbbgmhjblecj.crx/file
Go to chrome://extensions/ and enable developer mode at the top right, then just drag and drop the .crx file into the window.

**Comment by Charles2205** [comment]
Thanks

**Comment by joselmm** [comment]
I UPDATED THE EXTENSION TO MANIFEST V3,'
but due to the cors issue, I also had to update
the xdman.jr that is in the root folder of XDM,
YOU NEED TO DOWNLOAD my version of [xdman.jar](https://github.com/joselmm/xdm-2023/raw/main/xdman.jar) and replace the one in the root folder (DON'T FORGET TO GO TO "File" --> "Exit" first).

YOU MUST ENABLE DEVELOPER MODE IN CHROME, IN EXTENSIONS,
![1](https://github.com/subhra74/xdm/assets/95531879/c58eadd1-fb95-495b-820f-7f2fcb3370e5)


[HERE IS THE EXTENSION](https://github.com/joselmm/xdm-2023/raw/main/xdm-extesion-manifest-v3.zip). YOU MUST UNZIP AND DRAG AND DROP THE "xdm-extesion-manifest-v3" FOLDER
![2](https://github.com/subhra74/xdm/assets/95531879/67435c03-822a-4625-9166-574a5ec2b2a2)
THEN IT MUST APPEAR LIKE THIS:
![3](https://github.com/subhra74/xdm/assets/95531879/9727e8b6-ae3e-43ff-bdb3-a976a36e783f)


THIS IS MY VERSION OF xdman.jar:
![4](https://github.com/subhra74/xdm/assets/95531879/01c45dc3-e82d-4b4c-976a-b547ffc03090)
