### ISSUE TITLE
XDM Browser Monitor 2.0  not working in chrome extension

### ISSUE THREAD

**Issue by NahianAhmed** [subhra74/xdm#953]
Manifest version 2 is deprecated, and support will be removed in 2023. 
See https://developer.chrome.com/blog/mv2-transition/ for more details.
 -> [error log](https://ibb.co/0YtBfYK)

**Comment by Damilarondo** [comment]
Try the new betas link:https://github.com/subhra74/xdm-experimental-binaries/tags
Those versions were updated last two years ago

**Comment by joselmm** [comment]
I UPDATED THE EXTENSION TO MANIFEST V3,'
but due to the cors issue, I also had to update
the xdman.jr that is in the root folder of XDM,
YOU NEED TO DOWNLOAD my version of [xdman.jar](https://github.com/joselmm/xdm-2023/raw/main/xdman.jar) and replace the one in the root folder (DON'T FORGET TO GO TO "File" --> "Exit" first).

YOU MUST ENABLE DEVELOPER MODE IN CHROME, IN EXTENSIONS,
![1](https://github.com/subhra74/xdm/assets/95531879/c58eadd1-fb95-495b-820f-7f2fcb3370e5)


[HERE IS THE EXTENSION](https://github.com/joselmm/xdm-2023/raw/main/xdm-extesion-manifest-v3.zip). YOU MUST UNZIP AND DRAG AND DROP THE "xdm-extesion-manifest-v3" FOLDER
![2](https://github.com/subhra74/xdm/assets/95531879/67435c03-822a-4625-9166-574a5ec2b2a2)
THEN IT MUST APPEAR LIKE THIS:
![3](https://github.com/subhra74/xdm/assets/95531879/9727e8b6-ae3e-43ff-bdb3-a976a36e783f)


THIS IS MY VERSION OF xdman.jar:
![4](https://github.com/subhra74/xdm/assets/95531879/01c45dc3-e82d-4b4c-976a-b547ffc03090)
